
development:
  adapter: postgresql
  encoding: unicode
  database: first-quarterly-project_development
  pool: 5
  username: stephenreid
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: first-quarterly-project_development
  pool: 5
  username: stephenreid
  password: